version: '3.5'
services:
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.8.1-management
    ports: 
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
    restart: always